// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddrcidbvmdukwlhtiagx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkcmNpZGJ2bWR1a3dsaHRpYWd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MDY2OTEsImV4cCI6MjA1OTA4MjY5MX0.M5nyXVLOBQ5Mla3F96aVP6Qnap4kyIyaZBE3kPOZkqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);